version: 1.0
deploy:

  # configuration part, which is taken at the FIRST deployment of each branch
  bootstrap:
    # folders that are not copied to IONOS webspace
    excludes:
      - tests
      - node_modules
      # the following three files are generated during composer action and are not neccessary
      - DOCKER_ENV
      - docker_tag
      - output.log
    # commands that are executed at the real webspace NOT at build servers AFTER copying new files
    post-deployment-remote-commands:
      # create sqlite database file at first deployment
      - mkdir storage/logs
      - touch storage/database.sqlite
      ## IMPORANT ##
      ## You need to specify the php version with appendix cli, like php8.0-cli or php7.4-cli
      ## php without version or executing ./artisan directly is leading to use PHP 4.4
      - php8.0-cli artisan down
      # set right file permissions for Laravel
      - find $(pwd) -type f -not -path "$(pwd)/logs/*" -exec chmod 664 {} \;
      - find $(pwd) -type d -not -name "logs" -exec chmod 775 {} \;
      - chmod -R o+w storage bootstrap/cache
      # clear caches, migrate database, link storage, warmup caches
      - php8.0-cli artisan optimize:clear
      - php8.0-cli artisan migrate --force -n
      - php8.0-cli artisan storage:link
      - php8.0-cli artisan optimize
      - php8.0-cli artisan up

  # configuration part, which is taken at ALL FURTHER deployments of this branch
  recurring:
    excludes:
      - tests
      - node_modules
      - DOCKER_ENV
      - docker_tag
      - output.log
      # the storage folder shouldn't be synced after first deployment, because there
      # are files inside from running the Laravel app (e.g. database)
      - storage
    # commands that are executed at the real webspace NOT at build servers BEFORE copying new files
    pre-deployment-remote-commands:
      - php8.0-cli artisan down
    post-deployment-remote-commands:
      - find $(pwd) -type f -not -path "$(pwd)/logs/*" -exec chmod 664 {} \;
      - find $(pwd) -type d -not -name "logs" -exec chmod 775 {} \;
      - chmod -R o+w storage bootstrap/cache
      - php8.0-cli artisan optimize:clear
      - php8.0-cli artisan migrate --force -n
      - php8.0-cli artisan storage:link
      - php8.0-cli artisan optimize
      - php8.0-cli artisan up
